services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5434:5432
    env_file:
      - .env.test
      
  drivenpass:
    build: .
    container_name: drivenpass
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env.test